SET NAMES utf8mb4;

-- ============================================================
-- V16: 에어컨 개별 식별 No. 및 실외기 연결 정보
--   - 에어컨 제조사/설치연도/위치/실외기 개수 저장
--   - 실외기 좌표 저장 후 도면에서 실내기와 실외기 연결선 표시
-- ============================================================

ALTER TABLE facility_equipment
    ADD COLUMN IF NOT EXISTS MANUFACTURER VARCHAR(100) NULL COMMENT '제조사' AFTER EQUIPMENT_TYPE,
    ADD COLUMN IF NOT EXISTS INSTALLATION_YEAR INT NULL COMMENT '설치연도' AFTER MANUFACTURER,
    ADD COLUMN IF NOT EXISTS LOCATION_DESCRIPTION VARCHAR(200) NULL COMMENT '설비 위치 설명' AFTER INSTALLATION_YEAR,
    ADD COLUMN IF NOT EXISTS OUTDOOR_UNIT_COUNT INT NOT NULL DEFAULT 1 COMMENT '실외기 개수(1~2)' AFTER LOCATION_DESCRIPTION,
    ADD COLUMN IF NOT EXISTS OUTDOOR_X DECIMAL(9,4) NULL COMMENT '실외기 도면 X 좌표' AFTER Y,
    ADD COLUMN IF NOT EXISTS OUTDOOR_Y DECIMAL(9,4) NULL COMMENT '실외기 도면 Y 좌표' AFTER OUTDOOR_X;

UPDATE facility_equipment
SET OUTDOOR_UNIT_COUNT = 1
WHERE OUTDOOR_UNIT_COUNT IS NULL OR OUTDOOR_UNIT_COUNT < 1;

UPDATE facility_equipment
SET OUTDOOR_UNIT_COUNT = 2
WHERE OUTDOOR_UNIT_COUNT > 2;
