SET NAMES utf8mb4;

-- ============================================================
-- V31: 기타설비 모바일 QR 업무 기록 추가
--   - 에어컨 QR: 모바일 고장 접수 기록
--   - 정수기 QR: 모바일 소독 완료 사진 기록
-- ============================================================

CREATE TABLE IF NOT EXISTS facility_aircon_fault_report (
    REPORT_ID BIGINT NOT NULL AUTO_INCREMENT,
    EQUIPMENT_ID BIGINT NOT NULL,
    REPORTER_NAME VARCHAR(100) NULL,
    REPORTER_PHONE VARCHAR(50) NULL,
    FAULT_DESCRIPTION VARCHAR(1000) NOT NULL,
    PHOTO_PATH VARCHAR(600) NULL,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'RECEIVED',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (REPORT_ID),
    KEY IDX_FACILITY_AIRCON_FAULT_EQUIPMENT (EQUIPMENT_ID),
    KEY IDX_FACILITY_AIRCON_FAULT_CREATED (CREATED_AT),
    CONSTRAINT FK_FACILITY_AIRCON_FAULT_EQUIPMENT
        FOREIGN KEY (EQUIPMENT_ID) REFERENCES facility_equipment (EQUIPMENT_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS facility_water_disinfection (
    DISINFECTION_ID BIGINT NOT NULL AUTO_INCREMENT,
    EQUIPMENT_ID BIGINT NOT NULL,
    DISINFECTION_DATE DATE NOT NULL,
    WORKER_NAME VARCHAR(100) NOT NULL,
    NOTE VARCHAR(500) NULL,
    PHOTO_PATH VARCHAR(600) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (DISINFECTION_ID),
    KEY IDX_FACILITY_WATER_DISINFECTION_EQUIPMENT (EQUIPMENT_ID),
    KEY IDX_FACILITY_WATER_DISINFECTION_DATE (DISINFECTION_DATE),
    CONSTRAINT FK_FACILITY_WATER_DISINFECTION_EQUIPMENT
        FOREIGN KEY (EQUIPMENT_ID) REFERENCES facility_equipment (EQUIPMENT_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
