SET NAMES utf8mb4;

-- 정수기 QR 물통 사용/보급 이력. 기존 점검(facility_water_disinfection) 이력과 분리한다.
CREATE TABLE IF NOT EXISTS facility_water_consumption (
    CONSUMPTION_ID BIGINT NOT NULL AUTO_INCREMENT,
    EQUIPMENT_ID BIGINT NOT NULL,
    CONSUMPTION_DATE DATE NOT NULL,
    BOTTLE_COUNT INT NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NULL,
    PRIMARY KEY (CONSUMPTION_ID),
    KEY IDX_FACILITY_WATER_CONSUMPTION_EQUIPMENT_DATE (EQUIPMENT_ID, CONSUMPTION_DATE),
    CONSTRAINT FK_FACILITY_WATER_CONSUMPTION_EQUIPMENT
        FOREIGN KEY (EQUIPMENT_ID) REFERENCES facility_equipment (EQUIPMENT_ID)
        ON DELETE CASCADE,
    CONSTRAINT CK_FACILITY_WATER_CONSUMPTION_BOTTLES CHECK (BOTTLE_COUNT BETWEEN 1 AND 9)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
