-- ============================================================
--  module-common : 사용자 프로필·부서 스키마
--  MariaDB 10.11+ (utf8mb4)
--
--  원본: V1.0.0__init_schema.sql (MOD_USER_ 섹션)
--  의존: CORE_USER 테이블 (core 모듈)
-- ============================================================

-- ── 부서 테이블 ──
CREATE TABLE IF NOT EXISTS MOD_USER_DEPARTMENT (
    DEPT_ID        BIGINT       NOT NULL AUTO_INCREMENT  COMMENT '부서 ID (PK)',
    DEPT_NAME      VARCHAR(100) NOT NULL                 COMMENT '부서명',
    DEPT_CODE      VARCHAR(20)  NOT NULL                 COMMENT '부서 코드',
    PARENT_DEPT_ID BIGINT       NULL                     COMMENT '상위 부서 ID',
    SORT_ORDER     INT          NULL     DEFAULT 0       COMMENT '정렬 순서',
    ENABLED        TINYINT(1)   NOT NULL DEFAULT 1       COMMENT '활성화 여부',
    CREATED_AT     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT     DATETIME     NULL     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',

    PRIMARY KEY (DEPT_ID),
    CONSTRAINT UK_MOD_USER_DEPT_CODE UNIQUE (DEPT_CODE),
    CONSTRAINT FK_MOD_USER_DEPT_PARENT FOREIGN KEY (PARENT_DEPT_ID)
        REFERENCES MOD_USER_DEPARTMENT (DEPT_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
  COMMENT='부서';


-- ── 사용자 프로필 테이블 ──
CREATE TABLE IF NOT EXISTS MOD_USER_PROFILE (
    PROFILE_ID   BIGINT       NOT NULL AUTO_INCREMENT  COMMENT '프로필 ID (PK)',
    USER_ID      BIGINT       NOT NULL                 COMMENT '사용자 ID (CORE_USER 참조)',
    DEPT_ID      BIGINT       NULL                     COMMENT '부서 ID (MOD_USER_DEPARTMENT 참조)',
    POSITION     VARCHAR(50)  NULL                     COMMENT '직위',
    JOB_TITLE    VARCHAR(100) NULL                     COMMENT '직책',
    EMPLOYEE_NO  VARCHAR(20)  NULL                     COMMENT '사번',
    JOIN_DATE    DATE         NULL                     COMMENT '입사일',
    OFFICE_PHONE VARCHAR(20)  NULL                     COMMENT '사무실 전화번호',
    INTERNAL_EXT VARCHAR(10)  NULL                     COMMENT '내선번호',
    CREATED_AT   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT   DATETIME     NULL     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',

    PRIMARY KEY (PROFILE_ID),
    CONSTRAINT UK_MOD_USER_PROFILE_USER UNIQUE (USER_ID),
    CONSTRAINT FK_MOD_USER_PROFILE_USER FOREIGN KEY (USER_ID)
        REFERENCES CORE_USER (USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_MOD_USER_PROFILE_DEPT FOREIGN KEY (DEPT_ID)
        REFERENCES MOD_USER_DEPARTMENT (DEPT_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
  COMMENT='사용자 프로필';

CREATE INDEX IDX_MOD_USER_PROFILE_DEPT ON MOD_USER_PROFILE (DEPT_ID);
CREATE INDEX IDX_MOD_USER_PROFILE_EMP  ON MOD_USER_PROFILE (EMPLOYEE_NO);
