-- ============================================================
--  module-steam-energy : 업무 테이블 공통 컬럼(감사 · 소프트 삭제) 추가
--
--  업무 모듈 규격의 공통 컬럼 규칙을 steam_* 표에 맞춘다.
--    CREATED_BY / UPDATED_BY / DELETED_YN / DELETED_AT / DELETED_BY
--  (CREATED_AT / UPDATED_AT 은 이미 있음)
--
--  삭제는 물리 삭제하지 않고 DELETED_YN='Y' 로 처리한다.
--  엔티티에 @SQLRestriction("DELETED_YN = 'N'") 이 걸려 있어 조회에서 자동 제외된다.
--
--  이미 만들어진 DB 용 마이그레이션이다. 신규 설치는 01_schema.sql 에 반영돼 있어
--  이 파일을 실행해도 아무 것도 바뀌지 않는다(IF NOT EXISTS).
--  재실행 안전. DROP/TRUNCATE/무조건 DELETE 없음.
-- ============================================================

SET NAMES utf8mb4;

ALTER TABLE steam_equipment
    ADD COLUMN IF NOT EXISTS CREATED_BY BIGINT NULL COMMENT '생성자 사용자 ID' AFTER CREATED_AT,
    ADD COLUMN IF NOT EXISTS UPDATED_BY BIGINT NULL COMMENT '수정자 사용자 ID' AFTER UPDATED_AT,
    ADD COLUMN IF NOT EXISTS DELETED_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제 여부',
    ADD COLUMN IF NOT EXISTS DELETED_AT DATETIME NULL COMMENT '삭제일시',
    ADD COLUMN IF NOT EXISTS DELETED_BY BIGINT NULL COMMENT '삭제자 사용자 ID';

ALTER TABLE steam_price
    ADD COLUMN IF NOT EXISTS CREATED_BY BIGINT NULL COMMENT '생성자 사용자 ID' AFTER CREATED_AT,
    ADD COLUMN IF NOT EXISTS UPDATED_BY BIGINT NULL COMMENT '수정자 사용자 ID' AFTER UPDATED_AT,
    ADD COLUMN IF NOT EXISTS DELETED_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제 여부',
    ADD COLUMN IF NOT EXISTS DELETED_AT DATETIME NULL COMMENT '삭제일시',
    ADD COLUMN IF NOT EXISTS DELETED_BY BIGINT NULL COMMENT '삭제자 사용자 ID';

ALTER TABLE steam_daily_usage
    ADD COLUMN IF NOT EXISTS CREATED_BY BIGINT NULL COMMENT '생성자 사용자 ID' AFTER CREATED_AT,
    ADD COLUMN IF NOT EXISTS UPDATED_BY BIGINT NULL COMMENT '수정자 사용자 ID' AFTER UPDATED_AT,
    ADD COLUMN IF NOT EXISTS DELETED_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제 여부',
    ADD COLUMN IF NOT EXISTS DELETED_AT DATETIME NULL COMMENT '삭제일시',
    ADD COLUMN IF NOT EXISTS DELETED_BY BIGINT NULL COMMENT '삭제자 사용자 ID';

-- 소프트 삭제 조회용 인덱스
CREATE INDEX IF NOT EXISTS IDX_STEAM_EQUIPMENT_DELETED_YN   ON steam_equipment (DELETED_YN);
CREATE INDEX IF NOT EXISTS IDX_STEAM_PRICE_DELETED_YN       ON steam_price (DELETED_YN);
CREATE INDEX IF NOT EXISTS IDX_STEAM_USAGE_DELETED_YN       ON steam_daily_usage (DELETED_YN);
